services:
  configservice:
    image: "dhananjay75/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
  eurekaserver:
    image: "dhananjay75/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configservice:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
  accounts:
    image: "dhananjay75/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configservice:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  loans:
    image: "dhananjay75/loan:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configservice:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  loans1:
    image: "dhananjay75/loan:s8"
    container_name: loans-ms1
    ports:
      - "8091:8090"
    depends_on:
      configservice:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  cards:
    image: "dhananjay75/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - butterscotch
    environment:
      SPRING_APPLICATION_NAME: "cards"
#      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
#      SPRING_PROFILES_ACTIVE: default
    depends_on:
      eurekaserver:
        condition: service_healthy
      configservice:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config
networks:
  butterscotch:
    driver: "bridge"